### ISSUE TITLE
Feature Request: Support system-style questions

### ISSUE THREAD

**Issue by roy651** [instructlab/taxonomy#1106]
When defining a new skill in the pattern of question-context-answer it seems that ilab will generate all of those when it creates the augmented dataset. The implication is that they are all dynamically generated.

I would like to propose that ilab will support an additional entry in the skill's yaml allowing for a "system"-style which will preface the question when generating the answer. This part should be static and need not be generated for each new entry. Most likely, it should be static for the entire skill, hence it should reside in the top level of the yaml with the "task_description".

I think that this capability is something that may be required by additional skills as it follows, the now so common, system/user pattern and I assume others would require that too.

**Comment by jjasghar** [comment]
Please open up a proposal is the https://github.com/instructlab/dev-docs repo so we can have the discussion there. I'm going to close this because this discussion should happen there because it touches a bunch of this project not just taxonomy.

**Comment by obuzek** [comment]
Agreed that the proposal should be done elsewhere, but offering some quick context - part of the reason the current procedure does not expose the "system" part of the prompt is that the underlying LLM synthetic data generation (SDG) pipeline is using the "system" section to place the prompt for SDG.

See Figure 3 in the [LAB paper](https://arxiv.org/abs/2403.01081) here for an example.
