### ISSUE TITLE
Foundational Skills Missing?

### ISSUE THREAD

**Issue by anniedoris** [instructlab/taxonomy#1162]
**Describe the bug/problem**
Hi, I'm curious if there are foundational skills missing from the repo? In the LAB paper, it mentions that foundational skills was broken into several categories: mathematics, coding, linguistic ability, and reasoning. Currently in the repo, I only see the reasoning category. Is it possible that some categories are missing? Thanks for your help!

**Comment by juliadenham** [comment]
Not relevant any longer, closing.
