### ISSUE TITLE
Determine GitHub LFS impact on contributor experience

### ISSUE THREAD

**Issue by mairin** [instructlab/taxonomy#12]
Related to: https://github.com/open-labrador/cli/issues/62#issuecomment-1968292218

Over time the documents inside the taxonomy repo might get quite large.  Cloning a massive repository will be an impediment to first time contributors. So having all the documents download as part of the clone might not be a good idea.

There was a decision to require contributors submitting knowledge to submit the documents via git-lfs.

How does requiring LFS impact contributor experience both command line and GitHub UI? For both:

- contributors using git clients
- contributors using the GitHub UI

**Comment by bjhargrave** [comment]
@mairin Since we are not putting knowledge documents in the taxonomy repository, perhaps this issue can be closed?

**Comment by juliadenham** [comment]
Yes closing this issue.
