### ISSUE TITLE
Contributing to knowledge sports section

### ISSUE THREAD

**Issue by nvaibhav** [instructlab/taxonomy#1226]
**Describe the proposed contribution to the taxonomy**
The content that I want to contribute is to the knowledge of taxonomy.
I have added cricket in the sports/ and a qna.yaml and attribution files.

While working on instructlab , I downloaded the existing model and asked question -
Who won the 1987 cricket world cup ?
Ans: Yes, India did win the 1987 World Cup, which was the 50-over format of the Cricket World Cup tournament. India defeated the West Indies in the final match to │
│ claim victory. This marked their first World Cup title in cricket after several attempts.
It gave me wrong answer(above), since the information on wikipedia said otherwise.

Later I created qna file and fed in correct information, generated synthetic data, trained the model and tested again.
I asked the question , this time it gave me correct answer.

Hence this contribution.

- Corrected answer to 1987 cricket world cup winner.
- Gave inputs from wikipedia.
- Got correct information about hosting of this year world cup.

**Input given at the prompt**

```
   Did India win the 1987 world cup ?
```

**Response from the current model**

```
  Yes, India did win the 1987 World Cup, which was the 50-over format of the Cricket World Cup tournament. India defeated the West Indies in the final match to claim victory. This marked their first World Cup title in cricket after several attempts.
```

**Response that you would expect instead with the contribution**

```
   India did not win any matches in the 1987 cricket world cup, which was held in India and Pakistan.
```

After training the model, I asked bunch of questions, to which all the answers were correcrt.
Below are some of the questions I tried -
1. Who won the 1987 cricket world cup ?
Ans:Australia won the championship match against England by 7 runs, securing victory with just 23 balls left to spare.
2. Did India won the 1987 cricket world cup ?
Ans:No, India did not win the championship in 1987. They were knocked out during the group stage and finished in sixth place overall
3. Did Australia won the 1987 world cup ?
Ans: Australia won the championship match against England by a margin of just 7 runs, with both teams putting up an exceptional fight that came down to the final overs.
4. Who hosted the 1987 cricket world cup ?
Ans: India and Pakistan jointly hosted the 1987 tournament, marking the first time that the event was held outside England.

I created a fork and tried to check in got error.
Below is the cmds I tried along with the error -
```
(venv) vainakil@Vaibhavs-MacBook-Pro taxonomy % git push --set-upstream origin knowledge_cricket
Username for 'https://github.com': nvaibhav
Password for 'https://nvaibhav@github.com':
remote: Permission to instructlab/taxonomy.git denied to nvaibhav.
fatal: unable to access 'https://github.com/instructlab/taxonomy.git/': The requested URL returned error: 403
```

**Comment by jjasghar** [comment]
Yep, you need to create a fork in your namespace of `nvaibhav` so github.com/navibhav/taxonomy. If you look at the top of the taxonomy github page on the right hand side there is a "fork" button.

You can look through the [GitHub workflow](https://docs.github.com/en/get-started/using-github/github-flow) for more detailed explainations.

**Comment by nvaibhav** [comment]
Forked here - https://github.com/nvaibhav/taxonomy

**Comment by jjasghar** [comment]
I would suggest going to the #users channel in the slack team, or joining one of the office hours, debugging this via a github issue will be difficult.
