### ISSUE TITLE
Use YAML for attribution file format

### ISSUE THREAD

**Issue by IBMAnne** [instructlab/taxonomy#1231]
Right now, an attribution file is just a text file with expected keywords but no format. This is an excellent YAML use-case, where an actual schema could be used to organize the data into lists, similar to the Q&A YAML files.

**Comment by jjasghar** [comment]
This was chosen by the lawyers from the Project. We cannot change this without dealing with the legal team and what they are looking for.
As much as this from a technical conversation is a great idea, this is out of our hands as this project goes.

**Comment by IBMAnne** [comment]
Ok, thanks for the quick response!
