### ISSUE TITLE
Knowledge has an incompatible new v3 file format

### ISSUE THREAD

**Issue by markmc** [instructlab/taxonomy#1253]
See instructlab/sdg#160

A new v3 knowledge format has been added to InstructLab, with no backwards compatibility for v1 or v2 contributions - this till be released in InstructLab v0.18.0.

Existing knowledge contributions need to be updated, along with any documentation on creating knowledge contributions.

https://github.com/instructlab/instructlab/blob/main/scripts/test-data/e2e-qna-knowledge.yaml is an example of the new format

**Comment by bjhargrave** [comment]
We have existing v1 knowledge in the main branch which needs to be fixed or removed.

**Comment by markmc** [comment]
xref #1260

**Comment by markmc** [comment]
v3 example: #1255

**Comment by markmc** [comment]
From @juliadenham :+1: 

> The yaml file must include a minimum of 5 context fields, each with a minimum of 3 Q&A pairs relating to the context.
>
> Context should be a chunk from the knowledge document(s) being submitted and should be in markdown format.
>
> Length constraints:
>   500 words for context
>   250 words for Q&A pairs
>   750 total
>
> Document_outline is a new field that replaces task_description. It should describe the information noting specifics from each context hunk.

**Comment by juliadenham** [comment]
We now support V3 knowledge, yay!
