### ISSUE TITLE
qna.yaml access to a private repo with authentication and authorization

### ISSUE THREAD

**Issue by ridvan70** [instructlab/taxonomy#1258]
Hi, 
How can I access to knowledge MD files residing in private git repos?

Thanks,
Ridvan

**Comment by jjasghar** [comment]
For the upstream model? No. 

If you build up the infrastructure to train the model, technically, you can, but we don't have instructions on how to do that at this exact moment.

With this project's productization, there will be some turnkey options 🔜 keep an eye out for those!
