### ISSUE TITLE
Why do you not want code related information in the Taxonomy?

### ISSUE THREAD

**Issue by apcameron** [instructlab/taxonomy#1342]
The documentation states that you do not want Code related submissions.
   

>  "Anything code-related that can be traced back to code for a computer. Not limited to sed or bash but yamls for OpenShift or Kubernetes, to python snippets to Java suggestions. There are specific models focused on this space and this isn't for this model for the time being."

What is the reason for this?
It would be nice to use this to fine tune code related models.

An Example I found of this is [https://developer.ibm.com/tutorials/awb-train-open-source-llms-collected-skills-instructlab/](url)

**Comment by jjasghar** [comment]
The short answer is that it doesn't work. Long answer is the base models we use have a core data set and code isn't part of it. 

Then why not use something like granite-code or the like? Alas we tried and it doesn't work as expected. It's been deprioritized for the time being and maybe revisited in the future. 

I'll close this for now, if you have more questions don't hesitate to reopen or comment again.
