### ISSUE TITLE
Process for reporting problematic content?

### ISSUE THREAD

**Issue by wking** [instructlab/taxonomy#536]
We already have [a community code of conduct][1] and [a list of topics to avoid][2].  But:

* Contributors may open issues and pull requests with problematic content, before anyone project-side can review them for compliance.
* Review is manual and for some criteria subjective, and problematic content may slip past pre-merge review and land in the repository.
* Standards may evolve, and content that was acceptable at merge-time may match later iterations of problematic-content classifiers.

So while [asking triagers to review for HAP and such][3] is good, we also want to have a clear reporting pipeline for anyone who considers content problematic.  Currently [the code of conduct][4] suggests:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the [project team](https://github.com/instruct-lab/community/blob/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/MAINTAINERS.md). All complaints will be reviewed and investigated...

But there are a number of teams in that `MAINTAINERS.md`, and it's not clear from the docs whether it means [Taxonomy Maintainters][5] or [Community Maintainers][6] for someone who wants to report possibly-problematic content in the taxonomy repository.  It's also unclear, given a list of GitHub IDs, how those maintaner-sets should be contacted once the relevant set has been selected.

To address this issue, can we:

* Decide what the reporting pipeline is for problematic content review.  Maybe we want to recycle the code-of-conduct pipeline, and if so, clarifying that pipeline should probably be part of this issue (but clarifying that pipeline is a good idea even if we decide not to use it for problematic-content reporting).
* Document the selected reporting pipeline somewhere.  Probably somewhere in the community repository, so it can be shared with the `cli` and other repositories, which might also have problematic content.  Unless the criteria for problematic content are differernt per-repo, e.g.  [this list of  topics to avoid][2] comes underneath a big drawing of the taxonomy hierarchy, so it isn't immediately clear if it applies to the `cli` repo as well, or if it's specific to the `taxonomy` repo.
* Add links to places we think problematic-content-reporters might look, so they can find the reporting-pipeline documentation, and are less likely to submit a public GitHub issue or something else that might draw unwanted attention to the problematic content.  This likely includes at least:
    * New-issue GitHub templates for "report problematic content" where the message is "don't do this via an issue!  Instead see..." or similar.
    * The security docs, definitely [at the project level][8], possibly also [at the repository level][7], with a message like "[Problematic content](...) is not a security issue.  Report that via...".
    * [Contributing docs][9].
    * Possibly [the code of conduct][10], if we want to talk about the space between [what is (un)acceptable in community discussion][11] and [what is (un)acceptable in the taxonomy][2].  For example, current politics is [not appropriate for the taxonomy][2], but as far as I can tell [not a problem in community discussion][11] (as a topic, obviously constraints like "[Being respectful...][11]" still apply to that community discussion.  But maybe the gap is small enough that we want to collapse these categories, and not bother trying to distinguish between them?
    
We probably _also_ want some kind of periodic review, where project maintainers review at least open tickets and Git content for compatibility with the current standards.  But I'll leave that out of scope for this issue, and we can come back to it after we've worked out the reporting pipeline.

[1]: https://github.com/instruct-lab/community/blob/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/CODE_OF_CONDUCT.md
[2]: https://github.com/instruct-lab/community/tree/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/docs#avoid-these-topics
[3]: https://github.com/instruct-lab/taxonomy/blob/5ed705c7c20cb0dab42269a18987e263168b1f0b/docs/skills-triage.md#basic-review-questions
[4]: https://github.com/instruct-lab/community/blob/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/CODE_OF_CONDUCT.md#enforcement
[5]: https://github.com/instruct-lab/community/blob/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/MAINTAINERS.md?plain=1#L62
[6]: https://github.com/instruct-lab/community/blob/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/MAINTAINERS.md?plain=1#L40
[7]: https://github.com/instruct-lab/taxonomy/blob/5ed705c7c20cb0dab42269a18987e263168b1f0b/SECURITY.md
[8]: https://github.com/instruct-lab/community/blob/6cb8c22b320ec903e7d3f31e71b3d2fc7c872694/SECURITY.md
[9]: https://github.com/instruct-lab/taxonomy/blob/5ed705c7c20cb0dab42269a18987e263168b1f0b/CONTRIBUTING.md
[10]: https://github.com/instruct-lab/taxonomy/blob/5ed705c7c20cb0dab42269a18987e263168b1f0b/CODE_OF_CONDUCT.md
[11]: https://github.com/instruct-lab/taxonomy/blob/5ed705c7c20cb0dab42269a18987e263168b1f0b/CODE_OF_CONDUCT.md#our-standards

**Comment by juliadenham** [comment]
We now have this, closing.
