### ISSUE TITLE
What is the correct attribution when skill answers came from `lab chat` with modifications?

### ISSUE THREAD

**Issue by bbrowning** [instructlab/taxonomy#578]
I'm working on a skill where I generated examples by asking the existing default model (merlinite-7b-Q4_K_M.gguf) a question via `lab chat` and using that output as inspiration for the answer I want, correct formatting, removing extraneous / unrelated information from the response, and so on. This is a freeform writing skill, where the model is generating the content entirely by itself that is used as the basis of my corrected answer.

In this case, the question is my own but what is the correct attribution overall for these examples? How would I know the license of the underlying content that went into generating the answer it gave me? Or, do I consider all answers from this model as not encumbered by an existing license and I can choose to assign one myself, as if this was content I generated myself?

**Comment by jjasghar** [comment]
We have moved to the granite-3.0 model, I don't think this is something we will continue to investigate.
