### ISSUE TITLE
Proposal for adding capability of replying to close-ended questions in a concise way

### ISSUE THREAD

**Issue by bdattoma** [instructlab/taxonomy#613]
**Describe the proposed contribution to the taxonomy**

- When replying to a close ended question the model writes a lot
- If the prompt asks explicitly to response only with the option label (and maybe its value), the model does not respect the requirement
- Proposing to add a composite skill to reply only with the option label like in a close-ended question exam

**Input given at the prompt**

```
What the first law of robotics say? Return option number only: 
    1. A robot can hit a human if they are trying to hurt the robot;
    2. A robot may not injure a human being or, through inaction, allow a human being to come to harm;
    3. A human cannot interfere with robot action if this would mean making the robot failing a task
```

**Response from the current model**

```
   The first law of robotics, as stated by Isaac Asimov, is: "A robot may not injure a human being or, through inaction, allow a human being to come to harm." This is option 2 in the list provided.
```

**Response that you would expect instead with the contribution**

```
  2 or Option 2
```

**Comment by jjasghar** [comment]
We have updated to the granite-3.0 model, we would need to verify this is still an issue with it. Please reopen if this is something we should continue to investigate.

**Comment by bdattoma** [comment]
> > We have updated to the granite-3.0 model, we would need to verify this is still an issue with it. Please reopen if this is something we should continue to investigate.
> 
> thanks @jjasghar ! I'll give a try in the next days :D

I cannot try with the granite-3.0 model locally because I couldn't find a GGUF granite 3.0 (and I don't have a supported GPU for safetensors locally). I searched in  https://huggingface.co/instructlab and  https://huggingface.co/collections/ibm-granite/granite-30-language-models-66fdb59bbb54785c3512114f
