### ISSUE TITLE
Question: Can I turn off the teacher (question generation)?

### ISSUE THREAD

**Issue by TomasHofman** [instructlab/taxonomy#630]
What if I have a skill where it's easy to generate synthetic data in an algorithmic way (so I can generate 100 questions easily myself), and I'm not satisfied with the questions generated by the teacher model?

Can I turn it off?

Or is there a way for me to influence the teacher model in some way?

Example (Semantic version skill):

In the `qna.yaml`, I have questions like:

> Sort following version string from lowest to highest: 1.2.3, 2.2.1, 1.0.1
> Which of these versions belong to major version 1: 2.1.1, 1.2.0, 11.1.0

The generated questions are sometimes way off, like:

> Determine the highest peak in the world for each continent.
> - Africa: Kilimanjaro (5,895 m)
> - Antarctica: Vinson Massif (4,892 m)

Other generated questions are about basic arithmetic.

**Comment by juliadenham** [comment]
This is math, closing.
