### ISSUE TITLE
Proposal for automated checks of knowledge submission

### ISSUE THREAD

**Issue by katesoule** [instructlab/taxonomy#658]
In order to release knowledge contributions to open source community, IBM legal is asking us to propose an automated solution for our generation pipeline that covers:

On the provided knowledge source from the contributor:
- HAP detection
- PII detection
- Screening for commonly copyrighted content (e.g. OneShield) -- lower priority

On the synthetic data created from the knowledge source
- Screening for leakage of text from the knowledge source being used verbatim in the synthetic data (leveraging OneShield)

**Comment by juliadenham** [comment]
Closing as we now work with Red Hat legal.
