### ISSUE TITLE
instruct-lab-bot precheck issues

### ISSUE THREAD

**Issue by luke-inglis** [instructlab/taxonomy#667]
1. it seems that it is currently using Llama formatting opposed to the Merlinite. 
```
sys_prompt = "You are an AI language model developed by IBM Research. You are a cautious assistant. You carefully follow instructions. You are helpful and harmless and you follow ethical guidelines and promote positive behavior."

prompt = f'<|system|>\n{sys_prompt}\n<|user|>\n{inputs}\n<|assistant|>\n'
stop_token = '<|endoftext|>'
```
2. It also seems to be running multi turn at some points https://instruct-lab-bot.s3.us-east-2.amazonaws.com/precheck-pr-659-00158ec82c7eb42f338c29d67edce3cf21aac016/chat_2024-04-08T19_40_51.log

**Comment by bjhargrave** [comment]
@luke-inglis Is this issue still a problem? Perhaps we can close this issue if not.
