### ISSUE TITLE
Skill to support Gen AI guardrails

### ISSUE THREAD

**Issue by cmar28** [instructlab/taxonomy#766]
Hi,
I am would like to contribute skills to use as a base for fine tuning model to implement AI guardrails (ex PII detection, HAP detection), but also more nuanced content classifications to determine if a content is appropriate in the content of a specific use case (ex Education, Healthcare/Financial services). Is any work already happening in that space? Can you advise where should I put my examples in the taxonomy?
Thx

**Comment by jjasghar** [comment]
Hi! Yep, there is a gap in our model. thanks for finding and highlighting it. Unfortunately, we will wait for our "upstream" engineering team to deal with anything "guardrails" related. 

We'll update the avoid list to mention this soon, and thank you again for offering to help.
