### ISSUE TITLE
Training model logs 'nan' in message

### ISSUE THREAD

**Issue by konan-abhi** [instructlab/taxonomy#785]
While training the model, I can see below warning;

Training
/Users/akekane/instructlab/venv/lib/python3.12/site-packages/instructlab/train/lora_mlx/lora.py:130: RuntimeWarning: invalid value encountered in scalar divide
return np.sum(all_losses) / ntokens
Epoch 1: Iter 1: Val loss nan, Val took 0.002s

Epoch 50: Iter 50: Val loss nan, Val took 0.000s

"Val loss nan" is nan expected?

**Comment by jjasghar** [comment]
Is this still an issue for you? What version of `ilab` are you using? Have you tried again?

**Comment by konan-abhi** [comment]
This was the initial version, unfortunately I had to format my machine and haven't configured it again, But AFAIK this issue is still active.

**Comment by juliadenham** [comment]
Closing this as the code has changed drastically since this was opened. If you are still seeing this problem, please open an issue in the instructlab repo
