### ISSUE TITLE
Matthew Perry

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#790]
**Topic:** Mathew Langford Perry was an American and Canadian actor. He gained international fame for starting as chandler bing on TV sitcom Friends

**Folder Location:**  taxonomy/knowledge/pop_culture/celeberties/mathew_perry

**Downloads:** qna.yaml and attribution.txt 

**Wiki link:**  https://en.wikipedia.org/wiki/Matthew_Perry

**Comment by alimaredia** [comment]
No longer needed
