### ISSUE TITLE
Pancreaticoduodenectomy (surgery) 

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#801]
**Topic:** A pancreaticoduodenectomy, also known as a Whipple procedure, is a major surgical operation most often performed to remove cancerous tumors from the head of the pancreas.

**Folder Location:** taxonomy/knowledge/science/medical/pancreaticoduodenectomy

**Downloads:** 
- qna.yaml: [pancreaticoduodenectomy.txt](https://github.com/instructlab/taxonomy/files/15227004/pancreaticoduodenectomy.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15225919/pancre_attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Pancreaticoduodenectomy

**Comment by savva-k** [comment]
I will tackle this
