### ISSUE TITLE
Alto saxophone

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#803]
**Topic:** The alto saxophone is a member of the saxophone family of woodwind instruments. Saxophones were invented by Belgian instrument designer Adolphe Sax in the 1840s and patented in 1846.

**Folder Location:** taxonomy/knowledge/musical_instruments/alto_sax

**Downloads:** qna.yaml and [attribution.txt](https://github.com/instructlab/taxonomy/files/15227071/alto_sax_attribution.txt) 
[alto_sax.txt](https://github.com/instructlab/taxonomy/files/15227216/alto_sax.txt)

**Wiki link:** https://en.wikipedia.org/wiki/Alto_saxophone

**Comment by ibivibiv** [comment]
https://github.com/ibivibiv/taxonomy/tree/main/knowledge/musical_instruments/alto_sax
