### ISSUE TITLE
Wisdom tooth

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#807]
**Topic:** The third molar, commonly called wisdom tooth, is the most posterior of the three molars in each quadrant of the human dentition.

**Folder Location:** taxonomy/knowledge/science/anatomy/wisdom_teeth

**Downloads:** 
- qna.yaml: [wisdom_tooth.txt](https://github.com/instructlab/taxonomy/files/15226977/wisdom_tooth.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15225992/wt_attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Wisdom_tooth

**Comment by josh-friesen** [comment]
Working on this...
