### ISSUE TITLE
Baltimore classification

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#808]
**Topic:** Baltimore classification is a system used to classify viruses based on their manner of messenger RNA (mRNA) synthesis.

**Folder Location:** taxonomy/knowledge/science/biology/baltimore_clasification

**Downloads:** 
- qna.yaml: [Baltimore_class.txt](https://github.com/instructlab/taxonomy/files/15226967/Baltimore_class.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226051/baltimore-attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Baltimore_classification

**Comment by ibivibiv** [comment]
https://github.com/ibivibiv/taxonomy/tree/main/knowledge/science/biology/baltimore_clasification
