### ISSUE TITLE
2023 SAG-AFTRA strike

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#809]
**Topic:** From July 14 to November 9, 2023, the American actors' union SAG-AFTRA (Screen Actors Guild – American Federation of Television and Radio Artists) was on strike over a labor dispute with the Alliance of Motion Picture and Television Producers (AMPTP).

**Folder Location:** taxonomy/knowledge/history/events/SAG-AFTRA

**Downloads:** 
- qna.yaml: [SAG-AFTRA.txt](https://github.com/instructlab/taxonomy/files/15226965/SAG-AFTRA.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226019/2023-SAG-aftra-strike.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/2023_SAG-AFTRA_strike

**Comment by ibivibiv** [comment]
I'm starting to fill these out.  I have all of the bounties you put out last Friday.  I just need to dump them into yaml format and put them in my fork.  I am curious as to the format for attribution, do we put it as "wikipedia"?  I didn't find a ready example there.

https://github.com/ibivibiv/taxonomy/tree/main/knowledge/history/events

I'll upload the rest as the day continues and then probably wipe out the ones you put up today as well.
