### ISSUE TITLE
Prince Leopold Island

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#818]
**Topic:** [Prince Leopold Island](https://github.com/juliadenham/Summit_knowledge/blob/main/prince_leopold_island.md) is an island in the Qikiqtaaluk Region of Nunavut, Canada. It is located in Lancaster Sound at the junction of Prince Regent Inlet and Barrow Strait.

**Folder Location:** taxonomy/knowledge/geography/islands/prince_island

**Downloads:** 
- qna.yaml: [prince_leopold_island.txt](https://github.com/instructlab/taxonomy/files/15226922/prince_leopold_island.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226298/prince-leopold-island-attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Prince_Leopold_Island

**Comment by ckadner** [comment]
@kelbrown20 @juliadenham -- seems like the Markdown version of the wikipedia page is missing some numbers like the height of the cliffs surrounding the island

Wikipedia:

> ## Geography and Geology
> 
> Most of Prince Leopold Island rises steeply from the surrounding sea,
> with cliffs rising as **high as 265 m (869 ft) above sea** level surrounding
> most of the island.


Extracted Mardown:


> ## Geography and Geology
> 
> Most of Prince Leopold Island rises steeply from the surrounding sea,
> with cliffs rising as **high as above sea level** surrounding most of the
> island.
