### ISSUE TITLE
Interstate 84 

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#822]
**Topic:** Interstate 84  is an Interstate Highway in the Northeastern United States that extends from Dunmore, Pennsylvania to Sturbridge, Massachusetts.

**Folder Location:** taxonomy/knowledge/geography/highways/interstate_84

**Downloads:** 
- qna.yaml: [interstate_84.txt](https://github.com/instructlab/taxonomy/files/15226912/interstate_84.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226169/i84-attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Interstate_84_(Pennsylvania%E2%80%93Massachusetts)

**Comment by makelinux** [comment]
taking
