### ISSUE TITLE
DMC DeLorean

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#824]
**Topic:** The [DMC DeLorean](https://github.com/juliadenham/Summit_knowledge/blob/main/DMC_DeLorean.md) is a rear-engine two-passenger sports car manufactured and marketed by John DeLorean's DeLorean Motor Company.

**Folder Location:** taxonomy/knowledge/cars/delorean

**Downloads:** 
- qna.yaml: [DMC_delorean.txt](https://github.com/instructlab/taxonomy/files/15226908/DMC_delorean.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226113/delorean-attribution.txt) 

**Wiki link:**  https://en.wikipedia.org/wiki/DMC_DeLorean

**Comment by ckadner** [comment]
https://en.wikipedia.org/wiki/DMC_DeLorean#Performance

> DMC's comparison literature noted that the DeLorean could achieve **0–60 miles per hour (0–97 km/h)** in 8.8 seconds when equipped with a manual transmission, but other sources indicate an acceleration time of 9.5 seconds. When equipped with a manual transmission, the DeLorean accelerated **from 0 to 60 miles per hour (0 to 97 km/h)** in 10.5 seconds as tested by Road & Track magazine. Top speed was **claimed at 130 mph (209 km/h)**, but was tested to be a **lacking 110 mph (177 km/h)**. [Car & Driver](https://en.wikipedia.org/wiki/Car_%26_Driver) put the top speed of a 5-speed manual **at 117 mph (188 km/h) (indicated)**

https://github.com/juliadenham/Summit_knowledge/blob/main/DMC_DeLorean.md#performance

> DMC's comparison literature noted that the DeLorean could achieve in 8.8 seconds when equipped with a manual transmission, but other sources indicate an acceleration time of 9.5 seconds. When equipped with a manual transmission, the DeLorean accelerated **from** in 10.5 seconds as tested by Road & Track magazine. Top speed was **claimed at** , but was tested to be a **lacking .** [Car & Driver](https://github.com/juliadenham/Summit_knowledge/blob/main/Car_&_Driver) put the top speed of a 5-speed manual **at (indicated).**
