### ISSUE TITLE
Indian elephant

### ISSUE THREAD

**Issue by kelbrown20** [instructlab/taxonomy#831]
**Topic:** The Indian elephant is one of three extant recognized subspecies of the Asian elephant, native to mainland Asia. The species is smaller than the African elephant species. 

**Folder Location:** taxonomy/knowledge/animals/indian_elephant

**Downloads:** 
- qna.yaml: [indian_elephants.txt](https://github.com/instructlab/taxonomy/files/15226888/indian_elephants.txt)
- [attribution.txt](https://github.com/instructlab/taxonomy/files/15226173/indian-elephant-attribution.txt) 

**Wiki link:** https://en.wikipedia.org/wiki/Indian_elephant

**Comment by Bhavyajain21** [comment]
Hey @kelbrown20 , Can you please describe more about the issue?

**Comment by kelbrown20** [comment]
Got a lot of great contributions for this one. Closing for scannability, proceeding with the contributions
