### ISSUE TITLE
Linter Issue - "patterns:"

### ISSUE THREAD

**Issue by chipmc** [instructlab/taxonomy#904]
In the example on the documentation page, there is the following YAML:

 patterns:
   - oscars2024_results.md

This is valid YAML but it fails in the linter - the linter complains that "expected one space, found three"

Deleting the extra spaces resolves the issue but updating the documents in this way, would help:

- In the section "Skills: YAML Examples:" - complete the section to include the correct formatting for the "patterns:" section.  The current example stops at the questions and answers phase
- In the section "Knowledge: YAML Examples" - fix the spaces so it would pass the linter.

Thanks, 

Chip

**Comment by jjasghar** [comment]
This should be resolved, we have made our linter much better, and the examples should be more relevant now. If this is still a problem, please reopen this issue, and let's dig into it.
